app/home/forms.py
from flask import session
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, Field, TextAreaField
from wtforms.validators import DataRequired, Length, Regexp, Email, EqualTo, ValidationError

from app.models import User


class RegisterForm(FlaskForm):
    username = StringField(
        label='用户名：',
        validators=[
            DataRequired(message='用户名不能为空！'),
            Length(min=3, max=50, message='用户名长度必须在3-50位之间')
        ],
        description='用户名',
        render_kw={
            'type': 'text',
            'placeholder': '用户名',
            'class': 'validate-username',
            'size': 38,
        }
    )
    phone = StringField(
        label='联系电话：',
        validators=[
            DataRequired(message='手机号不能为空！'),
            Regexp("1[34578][0-9]{9}", message='手机号格式不正确')
        ],
        description='手机号',
        render_kw={
            'type': 'text',
            'placeholder': '联系电话',
            'size': 38,
        }
    )
    email = StringField(
        label='邮箱：',
        validators=[
            DataRequired(message='邮箱不能为空！'),
            Email(message='邮箱格式不正确'),
        ],
        description='邮箱',
        render_kw={
            'type': 'email',
            'placeholder': '邮箱',
            'size': 38,
        }
    )
    password = PasswordField(
        label='密码：',
        validators=[
            DataRequired(message='密码不能为空！'),
        ],
        description='密码',
        render_kw={
            'placeholder': '密码',
            'size': 38,
        }
    )
    re_password = PasswordField(
        label='确认密码：',
        validators=[
            DataRequired(message='请确认输入密码！'),
            EqualTo('password', message='两次输入密码不一致'),
        ],
        description='确认密码',
        render_kw={
            'placeholder': '确认密码',
            'size': 38,
        }
    )
    submit = SubmitField(
        label='同意协议并注册',
        render_kw={
            'class': 'btn btn-primary login',
        }
    )

    def validate_email(self, field: Field):
        email = field.data
        user_count = User.query.filter_by(email=email).count()
        if user_count >= 1:
            raise ValidationError('邮箱已存在！')

    def validate_phone(self, field: Field):
        phone = field.data
        user_count = User.query.filter_by(phone=phone).count()
        if user_count >= 1:
            raise ValidationError('手机号已存在!')


class LoginForm(FlaskForm):
    username = StringField(
        label='用户名：',
        validators=[
            DataRequired(message='用户名不能为空！'),
            Length(min=3, max=50, message='用户名长度必须在3-50位之间'),
        ],
        description='用户名',
        render_kw={
            'type': 'text',
            'placeholder': '用户名',
            'class': 'validate-username',
            'size': 38,
            'maxlength': 99,
        }
    )
    password = PasswordField(
        label='密码：',
        validators=[
            DataRequired("密码不能为空！"),
            Length(min=3, message="密码长度不少于6位")
        ],
        description='密码',
        render_kw={
            'type': 'password',
            'placeholder': '密码',
            'class': 'validate-password',
            'size': 38,
            'maxlength': 99,
        }
    )
    verify_code = StringField(
        label='验证码：',
        validators=[
            DataRequired(),
        ],
        render_kw={
            'class': 'validate-code',
            'size': 18,
            'maxlength': 4,
        }
    )
    submit = SubmitField(
        label='登录',
        render_kw={
            'class': 'btn btn-primary login',
        }
    )


class PasswordForm(FlaskForm):
    old_password = PasswordField(
        label="原始密码 ：",
        validators=[
            DataRequired("原始密码不能为空！")
        ],
        description="原始密码",
        render_kw={
            "placeholder": "请输入原始密码！",
            "size": 38,
        }
    )
    password = PasswordField(
        label="新密码 ：",
        validators=[
            DataRequired("新密码不能为空！")
        ],
        description="新密码",
        render_kw={
            "placeholder": "请输入新密码！",
            "size": 38,
        }
    )
    repassword = PasswordField(
        label="确认密码 ：",
        validators=[
            DataRequired("请输入确认密码！"),
            EqualTo('password', message="两次密码不一致！")
        ],
        description="确认密码",
        render_kw={
            "placeholder": "请输入确认密码！",
            "size": 38,
        }
    )
    submit = SubmitField(
        '确认修改',
        render_kw={
            "class": "btn btn-primary login",
        }
    )

    def validate_old_password(self, field: Field):
        old_password = field.data
        user_id = session['user_id']
        user = User.query.get(int(user_id))
        if not user.check_password(old_password):
            raise ValidationError('原始密码错误！')


class SuggetionForm(FlaskForm):
    """
    意见建议
    """
    name = StringField(
        label="姓名",
        validators=[
            DataRequired("姓名不能为空！")
        ],
        description="姓名",
        render_kw={
            "placeholder": "请输入姓名！",
            "class": "form-control"
        }
    )
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("邮箱不能为空！")
        ],
        description="邮箱",
        render_kw={
            "type": "email",
            "placeholder": "请输入邮箱！",
            "class": "form-control"
        }
    )
    content = TextAreaField(
        label="意见建议",
        validators=[
            DataRequired("内容不能为空！")
        ],
        description="意见建议",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入内容！",
            "rows": 7
        }
    )
    submit = SubmitField(
        '发送消息',
        render_kw={
            "class": "btn-default btn-cf-submit",
        }
    )

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__, url_prefix='/')

import app.home.views

app/home/views.py
import random
import string
from functools import wraps
from io import BytesIO
from typing import Tuple

from PIL import Image, ImageFont, ImageDraw
from flask import render_template, session, redirect, url_for, flash, make_response, request
from werkzeug.security import generate_password_hash

from app.models import Goods, User, Cart
from . import home
from .forms import RegisterForm, LoginForm, PasswordForm
from .. import db


def get_verify_code() -> Tuple:
    code = generate_text()
    width, height = 120, 50
    img = Image.new('RGB', (width, height), 'white')
    font = ImageFont.truetype(font='app/static/fonts/arial.ttf', size=40)
    draw = ImageDraw.Draw(img)
    for item in range(4):
        draw.text((5 + random.randint(-3, 3) + 23 * item, 5 + random.randint(-3, 3)),
                  text=code[item], fill=generate_color(), font=font)
    return img, code


def generate_text() -> str:
    letters_digits = string.ascii_letters + string.digits
    return ''.join(random.choice(letters_digits) for i in range(4))


def generate_color() -> Tuple:
    return random.randint(32, 127), random.randint(32, 127), random.randint(32, 127)


def login_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if "user_id" not in session:
            return redirect(url_for("home.login"))
        return f(*args, **kwargs)
    return wrap


@home.route('/')
def index():
    hot_goods = Goods.query.order_by(
        Goods.views_count.desc()).limit(2).all()
    new_goods = Goods.query.filter_by(is_new=1)\
        .order_by(Goods.addtime.desc()).limit(12).all()
    sale_goods = Goods.query.filter_by(is_sale=1)\
        .order_by(Goods.addtime.desc()).limit(12).all()

    return render_template('home/index.html', hot_goods=hot_goods, new_goods=new_goods, sale_goods=sale_goods)


@home.route('/register', methods=['GET', 'POST'])
def register():
    if 'user_id' in session:
        return redirect(url_for('home.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            password=generate_password_hash(form.password.data),
            phone=form.phone.data,
            email=form.email.data,
        )
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('home.login'))

    return render_template('home/register.html', form=form)


@home.route('/code')
def get_code():
    image, code = get_verify_code()
    buf = BytesIO()
    image.save(buf, 'jpeg')
    buf_str = buf.getvalue()
    response = make_response(buf_str)
    response.headers['Content-Type'] = 'image/gif'
    session['image'] = code
    return response


@home.route('/login', methods=['GET', 'POST'])
def login():
    if 'user_id' in session:
        return redirect(url_for('home.index'))

    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        verify_code = form.verify_code.data
        user = User.query.filter_by(username=username).first()

        if user is None:
            flash('用户名不存在！', 'err')
            return render_template('home/login.html', form=form)

        if not user.check_password(password):
            flash('密码错误！', 'err')
            return render_template('home/login.html', form=form)

        if session.get('image').lower() != verify_code.lower():
            flash('验证码错误！', 'err')
            return render_template('home/login.html', form=form)

        session['user_id'] = user.id
        session['username'] = user.username
        return redirect(url_for('home.index'))

    return render_template('home/login.html', form=form)


@home.route('/logout')
def logout():
    session.pop('user_id', None)
    session.pop('username', None)
    return redirect(url_for('home.login'))


@home.route('/modify_pwd', methods=['GET', 'POST'])
def modify_password():
    form = PasswordForm()
    if form.validate_on_submit():
        new_password = form.password.data
        user = User.query.filter_by(username=session['username']).first()
        user.password = generate_password_hash(new_password)
        db.session.add(user)
        db.session.commit()
        return "<script>alert('密码修改成功！'); location.href='/';</script>"

    return render_template('home/modify_password.html', form=form)


@home.route('/goods_detail/<int:goods_id>')
def goods_detail(goods_id: int):
    user_id = session.get('user_id', 0)
    goods = Goods.query.get_or_404(goods_id)
    type_id = request.args.get('type')
    goods.views_count = goods.views_count + 1
    db.session.add(goods)
    db.session.commit()

    hot_goods = Goods.query.filter_by(subcat_id=goods.subcat_id)\
        .order_by(Goods.views_count.desc()).limit(5).all()
    similar_goods = Goods.query.filter_by(subcat_id=goods.subcat_id)\
        .order_by(Goods.addtime.desc()).limit(5).all()

    return render_template('home/goods_detail.html', goods=goods, user_id=user_id,
                           type_id=type_id, hot_goods=hot_goods, similar_goods=similar_goods)


@home.route('/cart_add')
def cart_add():
    print(request.args.get('user_id'))
    cart = Cart(
        goods_id=request.args.get('goods_id'),
        number=request.args.get('number'),
        user_id=session.get('user_id', 0)   # 用户未登录默认为0
    )
    db.session.add(cart)
    db.session.commit()
    return redirect(url_for('home.shopping_cart'))


@home.route('/cart_clear')
@login_required
def cart_clear():
    user_id = session.get('user_id', 0)
    Cart.query.filter_by(user_id=user_id).update({'user_id': 0})
    db.session.commit()
    return redirect(url_for('home.shopping_cart'))


@home.route('/shopping_cart')
@login_required
def shopping_cart():
    user_id = session.get('user_id')
    carts = Cart.query.filter_by(user_id=user_id)\
        .order_by(Cart.addtime.desc()).all()
    total_price = Cart.get_total_price_by_user_id(user_id=user_id)
    if carts:
        return render_template('home/shopping_cart.html', carts=carts, total_price=total_price)
    else:
        return render_template('home/empty_cart.html')


@home.route('/goods_list/<int:supercat_id>')
def goods_list(supercat_id: int):
    page = request.args.get('page', 1, type=int)
    page_data = Goods.query.filter_by(supercat_id=supercat_id)\
        .paginate(page=page, per_page=12)
    hot_goods = Goods.query.filter_by(supercat_id=supercat_id)\
        .order_by(Goods.views_count.desc()).limit(7).all()
    return render_template('home/goods_list.html', page=page, page_data=page_data,
                           hot_goods=hot_goods, supercat_id=supercat_id)


@home.route('/search')
def goods_search():
    page = request.args.get('page', 1, type=int)
    keywords = request.args.get('keywords', '', type=str)
    if keywords:
        page_data = Goods.query.filter(Goods.name.like('%' + keywords + '%'))\
            .order_by(Goods.addtime.desc()).paginate(page=page, per_page=12)
    else:
        page_data = Goods.query.order_by(Goods.addtime.desc())\
            .paginate(page=page, per_page=12)
    hot_goods = Goods.query.order_by(Goods.views_count.desc()).limit(7).all()

    return render_template('home/goods_search.html', page_data=page_data, keywords=keywords, hot_goods=hot_goods)

app/templates/home/common.html
{% include 'home/header.html' %}

{% block content %}
    {# content #}
{% endblock %}

{% include 'home/footer.html' %}

app/templates/home/empty_cart.html
{% extends "home/common.html" %}

{% block content %}
	<!-- //网站头部 -->
    <div id="mr-mainbody" class="container mr-mainbody">
        <div class="row">
            <!-- 页面主体内容 -->
            <div id="mr-content" class="mr-content col-xs-12">
                <div id="mrshop" class="mrshop common-home">
                    <div class="container_oc">
                        <div class="container_oc">
                            <div class="breadcrumb"></div>
                        </div>
                        <div class="row">
                            <div id="content_oc" class="col-sm-12" style="min-height:300px;">
                                <h1>我的购物车</h1>
                                <div class="table-responsive cart-info" style="margin-bottom:50px;">您的购物车为空！</div>
                                <div class="buttons">
                                    <div class="pull-left">
                                        <a href="{{url_for('home.index')}}" class="btn btn-primary btn-default">继续购物</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- //页面主体内容 -->
        </div>
    </div>
{% endblock %}

app/templates/home/goods_search.html
{% extends "home/common.html" %}

{% block content %}
    <div id="mr-mainbody" class="container mr-mainbody">
        <div class="row">
            <div id="mr-content" class="mr-content col-xs-12 col-sm-12 col-md-9 col-md-push-3">
                <div id="system-message-container" style="display: none;"></div>
                <div id="mrshop" class="mrshop common-home">
                    <div class="container_oc">
                        <ul class="breadcrumb"></ul>
                        <div class="row">
                            <div id="content_oc" class="col-sm-12">
                                <div class="box_oc">
                                    <div class="box-heading">
                                        <h1 class="mrshop_heading_h1">搜索结果</h1>
                                    </div>
                                    <div class="box-content1">
                                        <hr>
                                        <div class="row">
                                            {% if page_data.items %}
                                                {% for item in page_data.items %}
                                                <div class="product-layout product-grid col-lg-3 col-md-3 col-sm-6 col-xs-12">
                                                <div class="product-thumb">
                                                    <div class="actions">
                                                        <div class="image">
                                                            <a href="/goods_detail/{{item.id}}?type={{item.supercat_id}}">
                                                                <img src="{{url_for('static',filename='images/goods/'+item.picture)}}"
                                                                class="img-responsive">
                                                            </a>
                                                        </div>
                                                        <div class="button-group btn-grid">
                                                            <div class="cart">
                                                                <button class="btn btn-primary btn-primary"
                                                                    type="button" data-toggle="tooltip"
                                                                    onclick='javascript:window.location.href="/cart_add?goods_id={{item.id}}&number=1"; '
                                                                    style="display: none; width: 33.3333%;"
                                                                    data-original-title="添加到购物车">
                                                                    <i class="fa fa-shopping-cart"></i>
                                                                </button>
                                                            </div>
                                                            <div class="wishlist">
                                                                <button class="btn" type="button" data-toggle="tooltip"
                                                                    title="收藏">
                                                                    <i class="fa fa-heart"></i>
                                                                </button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div>
                                                        <div class="caption">
                                                            <div class="name">
                                                                <a href="/goods_detail/{{item.id}}?type={{item.supercat_id}}" style="width: 95%">
                                                                    <span style="color: #0885B1">商品名称：</span>{{item.name}}</a>
                                                            </div>
                                                            <p class="price">
                                                                <span class="price-new">分类：</span> <span>{{item.subcat.cat_name}}</span>
                                                                <span class="price-tax">价格: {{item.current_price}}元
                                                                </span>
                                                            </p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                                {% endfor %}
                                            {% else %}
                                                <div style="text-align:center;font-size:16px;color:red">没有插叙到您想要的商品哦！</div>
                                            {% endif %}
                                        </div>
                                        <div class="row pagination">
                                            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                            <tr>
                                            <td height="30" align="right">
                                                {% if page_data.has_prev %}
                                                    <a href="{{ url_for('home.goods_search', page=page_data.prev_num, keywords=keywords) }}">上一页</a>
                                                {% endif %}
                                                {% if page_data.items %}
                                                    {% for page_num in page_data.iter_pages() %}
                                                        {% if page_num != page_data.page %}
                                                            <a href="{{ url_for('home.goods_search', page=page_num, keywords=keywords) }}">{{ page_num }}</a>
                                                        {% else %}
                                                            <a class="active" style="color: red;" href="{{ url_for('home.goods_search', page=page_num, keywords=keywords) }}">{{ page_num }}</a>
                                                        {% endif %}
                                                    {% endfor %}
                                                {% endif %}
                                                {% if page_data.has_next %}
                                                    <a href="{{ url_for('home.goods_search', page=page_data.next_num, keywords=keywords) }}">下一页</a>
                                                {% endif %}
                                            </td>
                                            </tr>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <h3 class="module-title">热门商品</h3>
            {% for item in hot_goods %}
                <div class="image">
                    <a href="{{ url_for('home.goods_detail', goods_id=item.id) }}">
                        <img src="{{ url_for('static', filename='images/goods/' + item.picture) }}" alt="">
                    </a>
                </div>
                <div class="name">
                    <a href="{{ url_for('home.goods_detail', goods_id=item.id) }}">
                        {{ item.name }}
                    </a>
                </div>
                <div class="price">
                    {{ item.current_price }} 元
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/home/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页 - 51商城</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='home/css/mr-01.css') }}" type="text/css">
    <script src="{{url_for('static',filename='home/js/jsArr01.js')}}" type="text/javascript"></script>
    <script src="{{url_for('static',filename='home/js/module.js')}}" type="text/javascript"></script>
    <script src="{{url_for('static',filename='home/js/jsArr02.js')}}" type="text/javascript"></script>
    <script src="{{url_for('static',filename='home/js/tab.js')}}" type="text/javascript"></script>
</head>

<body>
    <div id="toolbar" style="background-color: #F0F0F0; width: 100%;">
        <div class="container">
            <div class="row">
                <div class="toolbar-ct-1">
                    <p>
                        <i class="fa fa-phone"></i>
                        <span style="margin-right: 15px;">电话：400-675-1066</span>
                        {% if 'user_id' in session %}
                            您好，{{ session['username'] }}
                            &nbsp; &nbsp;<a href="{{ url_for('home.modify_password') }}">修改</a>&nbsp;&nbsp;
						    |&nbsp;&nbsp;<a href="{{ url_for('home.logout') }}">退出</a>
                        {% else %}
                            <a href="{{ url_for('home.login') }}">登录</a>&nbsp; ｜ &nbsp;<a href="{{ url_for('home.register') }}">注册</a>
                        {% endif %}
                    </p>
                </div>
                <div class="toolbar-ct-2">
                    <a href="#">我的订单</a>&nbsp;&nbsp; | &nbsp;&nbsp; 我的收藏
                </div>
            </div>
        </div>
        <div style="background-color: white; width: 100%;">
            <div class="container">
                <div class="row">
                    <div class="toolbar-ct col-xs-12 col-md-6 hidden-sm hidden-xs">
                        <div class="toolbar-ct-1">
                            <img src="{{ url_for('static', filename='home/images/51logo.png') }}" alt="">
                        </div>
                        <div>
                            <!-- 搜索条 -->
                            <div class="search_box">
                                <div class="top-nav-search">
                                    <form method="get" action="{{ url_for('home.goods_search') }}">
                                        <input type="text" name="keywords" size="38"
                                               style="border: 0px;" class="top-nav-search-input" placeholder="请输入内容" />
                                        <button type="submit" class="search_box_img" onfocus="this.blur()">
                                            <img src="{{ url_for('static', filename='home/images/search.png') }}"
                                                 style="alignment: center;" alt="">
                                        </button>
                                    </form>
                                </div>
                            </div>
                            <!-- 搜索条 -->
                        </div>
                    </div>
                    <div class="toolbar-ct toolbar-ct-right col-xs-12 col-md-3">
					<div class="toolbar-ct-2 "
						style="margin-top: 35px; border: 1px solid #EAEAEA; padding: 5px;">
						<a href="{{ url_for('home.shopping_cart') }}" style="color: #E33737; font-size: 20px;"><i
							class="fa fa-cart1"></i> 我的购物车</a>
					</div>
				</div>
                </div>
            </div>
        </div>
    </div>
    <header id="mr-header" class="wrap mr-header">
        <div class="container">
            <div class="row">
                <nav id="mr-mainnav" class="col-xs-12 col-md-6 mr-mainnav navbar navbar-default">
                    <div class="mr-megamenu animate slide" data-duration="400" data-responsive="true">
                        <ul class="nav navbar-nav level0">
                            <li itemprop="name" data-id="435" data-level="1">
                                <a id="index" itemprop="url" class="" href="{{ url_for('home.index') }}" data-target="#">
                                    首页
                                </a>
                            </li>
                            <li itemprop="name" data-id="510" data-level="1">
								<!--<a id="jingying" itemprop="url" class="" href="{{url_for('home.goods_list',supercat_id=14)}}" data-target="#">-->
								<a id="jingying" itemprop="url" class="" href="/goods_list/14?type=14" data-target="#">
									图书类
								</a>
							</li>
							<li itemprop="name" data-id="510" data-level="1">
								<a id="wenyi" itemprop="url" class="" href="/goods_list/15?type=15"
								data-target="#">家电类</a>
							</li>

							<li itemprop="name" data-id="510" data-level="1">
								<a id="jiaoyu" itemprop="url" class="" href="/goods_list/16?type=16"
								data-target="#">服装类</a>
							</li>
							<li itemprop="name" data-id="510" data-level="1">
								<a id="shenghuo" itemprop="url" class="" href="/goods_list/17?type=17"
								   data-target="#">电子类
								</a>
							</li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>
</body>
</html>

app/templates/home/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录 - 51商城</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='home/css/mr-01.css') }}" type="text/css">
</head>
<body>
    <div id="mr-mainbody" class="container mr-mainbody">
        <div class="row">
            <div id="mr-content" class="mr-content col-xs-12">
				<div class="login-wrap" style="margin-bottom: 60px; margin-top: 50px">
                    <a href="index.html" title="点击返回首页">
                        <img src="{{ url_for('static', filename='home/images/51logo.png') }}" alt="">
                    </a>
                </div>
                <div class="login">
                    <div class="page-header" style="pause: 0px;">
                        <h1 class="login_h1">会员登录</h1>
                    </div>
                    {% for msg in get_flashed_messages(category_filter=['err']) %}
                        <div style="color: red; text-align: center; font-size: 16px;">
                        {{ msg }}
                        </div>
                    {% endfor %}
                    <form action="" method="post" class="form-horizontal">
                        <fieldset>
                            <div class="form-group">
                                <div class="col-sm-4 control-label">
                                    {{ form.username.label }}
                                </div>
                                <div class="col-sm-8">
                                    {{ form.username }}
                                    {% for error in form.username.errors %}
                                        <span class="error">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-4 control-label">
                                    {{ form.password.label }}
                                </div>
                                <div class="col-sm-8">
                                    {{ form.password }}
                                    {% for error in form.password.errors %}
                                        <span class="error">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-4 control-label">
                                    {{ form.verify_code.label }}
                                </div>
                                <div class="col-sm-8">
                                    {{ form.verify_code }}
                                    <img class="img_checkcode" src="{{ url_for('home.get_code') }}" width="116"
                                         height="43" onclick="this.src='{{ url_for('home.get_code') }}' + '?' + Math.random()" alt="">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-4 col-sm-8">
                                    {{ form.csrf_token }}
                                    {{ form.submit }}
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>